Repository soracom/soratun, pull requests merged in 2021-07, with the labels that each got.

#8 docs: update building instruction
  docs/CONTRIBUTING.md
Labels: documentation

#9 feat: bash/zsh autocompletion
  README.md
  cmd/bootstrap.go
  cmd/bootstrap_authkey.go
  cmd/bootstrap_cellular.go
  cmd/bootstrap_sim.go
  cmd/completion.go
  cmd/config.go
  cmd/dump_wireguard_config.go
  cmd/root.go
  cmd/status.go
  cmd/up.go
  cmd/version.go
  go.mod
  go.sum
Labels: enhancement

#7 feat: support PostUp/PostDown
  cmd/dump_wireguard_config.go
  config.go
  docs/config.en.md
  docs/config.ja.md
  docs/schema/soratun-config.en.schema.json
  docs/schema/soratun-config.ja.schema.json
  network_darwin.go
  tunnel.go
Labels: enhancement

#10 Change it export the original (i.e. raw) Arc server endpoint to a configuration file
  cmd/config.go
  cmd/config_test.go
  config.go
  tunnel.go
Labels: bug

#11 Show the actual version and revision information through the `version` subcommand
  Makefile
  cmd/version.go
  internal/version.go
Labels: enhancement

#12 Put User-Agent HTTP header onto each HTTP request
  client.go
  internal/user_agent.go
  krypton_client.go
Labels: enhancement

#13 build: update goreleaser configuration with new internal structure
  .goreleaser.yml
Labels: chore

#17 Setup CodeQL
  .github/workflows/codeql-analysis.yml
Labels: chore
